// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' ;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9LMQEXGcsCaVvuEOVmLEVzYUaZZjXUU',
    appId: '1:763194011568:web:e9dc373372f29b98c2f075',
    messagingSenderId: '763194011568',
    projectId: 'vbasassa',
    authDomain: 'vbasassa.firebaseapp.com',
    storageBucket: 'vbasassa.firebasestorage.app',
    measurementId: 'G-RBLQ2DNV8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLuePHXz4uozrJ_ASTzUnGapBKc96T9lc',
    appId: '1:763194011568:android:95eab7373d300042c2f075',
    messagingSenderId: '763194011568',
    projectId: 'vbasassa',
    storageBucket: 'vbasassa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBChCOFb0XEwgBJoHk464xiO4wC8fiQAic',
    appId: '1:763194011568:ios:50e742884efe2cc2c2f075',
    messagingSenderId: '763194011568',
    projectId: 'vbasassa',
    storageBucket: 'vbasassa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBChCOFb0XEwgBJoHk464xiO4wC8fiQAic',
    appId: '1:763194011568:ios:50e742884efe2cc2c2f075',
    messagingSenderId: '763194011568',
    projectId: 'vbasassa',
    storageBucket: 'vbasassa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR9LMQEXGcsCaVvuEOVmLEVzYUaZZjXUU',
    appId: '1:763194011568:web:0a676482ba7ed495c2f075',
    messagingSenderId: '763194011568',
    projectId: 'vbasassa',
    authDomain: 'vbasassa.firebaseapp.com',
    storageBucket: 'vbasassa.firebasestorage.app',
    measurementId: 'G-VC1G9T2ZP0',
  );
}
